name: dplpy
channels:
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - argparse
  - bs4
  - ca-certificates
  - certifi
  - conda
  - jsonschema
  - libcurl
  - openssl
  - pip
  - python
  - python-dateutil
  - requests
  - wheel