name: dplpy
channels:
  - conda-forge
  - defaults
dependencies:
<<<<<<< HEAD
  - ca-certificates
  - cairo
  - certifi
  - folium
  - gdal
  - geojson
  - geos
  - json-c
  - jsonschema
  - libclang
  - libcurl
  - libgdal
 # - libgfortran-ng
 # - libgfortran5
 #- libnetcdf
  - matplotlib
  - matplotlib-base
  - numpy
  - pandas
  - pillow
  - pip
  - pkg-config
  - proj
  - python
  - python-dateutil
  - python_abi
  - rasterio
 # - readline
  - requests
  - urllib3
=======
  - bs4
  - numpy
  - pandas
  - python
>>>>>>> 12be64b5f9fd65842e1e99945077f50007cd95ef
